### ISSUE TITLE
Does this gem add support for JDBCMSSQL?

### ISSUE THREAD

**Issue by ghost** [cleblanc87/sqlserver-foreigner#1]
I have a project which uses Jruby and MSSQL server.  Would this gem add support for JRuby and the JDBCMSSQL active record adapter?  The README does not indicate that this gem would solve my current problem (that is, Foreigner does not support JDBC MSSQL natively).

**Comment by cleblanc87** [comment]
Have not tested on jruby, but be sure to share how it goes. This gem specifically patches in MSSQL onto foreigner. There is a MSSQL specific fork of foreigner here however https://github.com/cjheath/foreigner .

**Comment by ghost** [comment]
Thanks I'll give it a shot and see how it goes.  If I run into anything that I end up patching, I'll fork and submit a pull request.

**Comment by avinmathew** [comment]
The [activerecord-jdbc-adaptor gem](https://github.com/jruby/activerecord-jdbc-adapter) uses an [adapter name of "MSSQL"](https://github.com/jruby/activerecord-jdbc-adapter/blob/master/lib/arjdbc/mssql/adapter.rb#L228). So I get the following message:

```
Database adapter mssql not supported. Use:\nForeigner::Adapter.register 'mssql', 'path/to/adapter'
```

Is it possible to register 'mssql' in addition to 'sqlserver' in order to support JRuby?
